config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :boards
  
  resources :pins do
    member do
      post '/repost' => 'pins#repost'
    end

    member do
      post '/like' => 'pins#like'
    end
  end

  get ':username' => 'users#show', as: 'user'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :pins
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :pin
  validates_uniqueness_of :pin_id, scope: :user_id
end

app/models/pin.rb
class Pin < ApplicationRecord
  validates_presence_of :description
  belongs_to :user
  belongs_to :board

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  has_attached_file :pin_image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :pin_image, content_type: /\Aimage\/.*\Z/

  def repost(user)
    repost_pin = self.dup
    repost_pin.user_id = user.id
    repost_pin.original_pin_id = self.id
    repost_pin.pin_image = self.pin_image
    repost_pin.save
  end

  def is_repost?
    original_pin_id.present?
  end

  def original_pin
    Pin.find(original_pin_id) if is_repost?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :pins, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_pins, through: :likes, source: :pin
  has_many :boards

  validates_uniqueness_of :username

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:bio, :avatar])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @boards = Board.all
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to boards_path, notic: 'New boards was created!'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to boards_path, notice: 'The board was updated!'
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path, notice: 'The board was deleted!'
  end

  private
  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:name)
  end

  def correct_user
    @board = current_user.boards.find_by(id: params[:id])
    redirect_to boards_path, notice: "Not authorized to edit this board" if @board.nil?
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy, :repost, :like]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @pins = Pin.all
  end

  def show
    @pin = Pin.find(params[:id])
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
    @pin = Pin.find(params[:id])
  end

  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to pins_path, notice: 'Pin was successfully created.'
    else
      render :new
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url, notice: 'Pin was successfully destroyed.'
  end

  def repost
    @pin.repost(current_user)
    redirect_to pins_path
  end

  def like
    @like = @pin.likes.build(user_id: current_user.id)
    if @like.save
      flash[:notice] = "You liked this pin!"
      redirect_to pins_path
    else
      flash[:notice] = "You already liked this pin!"
      redirect_to pins_path
    end
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:description, :pin_image, :board_id)
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by username: params[:username]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_form.html.haml
= form_for @board do |f|
  - if @board.errors.any?
    #error_explanation
      %h2
        = pluralize(@board.errors.count, "error")
        prohibited this board from being saved:
      %ul
        - @board.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :name
    %br/
    = f.text_field :name, class: 'form-control'
  .actions
    = f.submit class: 'btn btn-primary'

app/views/boards/edit.html.haml
%h1 Edit Board
= render 'form'

app/views/boards/index.html.haml
%h2 All Boards
=link_to 'New Board', new_board_path

- @boards.each do |board|
  %div
    %h2= board.name
    %p
      = link_to 'Edit', edit_board_path(board)
      | #{link_to 'Delete', board, method: :delete, data: {confirm: 'Are you sure?'}}

app/views/boards/new.html.haml
%h1 New Board
= render 'form'

app/views/boards/show.html.haml
%h2= @board.name

.row.pin-grid.transitions-enabled
  - @board.pins.each do |pin|
    .col-md-3.pin-item
      .panel.panel-default.pin
        .panel-body
          = link_to image_tag(pin.pin_image.url(:medium)), pin
        .panel-footer.panel-custom
          %p= link_to pin.user.username, user_path(pin.user.username)
          %p= pin.description
          %p= pluralize(pin.likes.count, "like")
          - if pin.user == current_user
            %div
              = link_to 'Edit', edit_pin_path(pin)
              | #{link_to 'Delete', pin, method: :delete, data: {confirm: 'Are you sure?'}}
          - if user_signed_in? && pin.user != current_user
            %div
              = link_to 'Repost', repost_pin_path(pin), method: :post, data: {confirm: 'Are you sure?'}
              = link_to 'Like', like_pin_path(pin), method: :post, class: 'pull-right'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Sweet
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      %ul.nav.nav-tabs
        %li= link_to "Home", root_path
        %li= link_to "Pins", pins_path
        .pull-right.user-info
          - if user_signed_in?
            Signed in as:
            %strong= current_user.email
            |
            = link_to 'New Pin', new_pin_path
            |
            \#{link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link'} - #{link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'}
          - else
            = link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'
            \-
            \#{link_to "Sign In", new_user_session_path, :class => 'navbar-link'}
    - if flash[:notice]
      .alert.alert-success
        %button.close{"data-dismiss" => "alert", :type => "button"} ×
        = flash[:notice]
    - elsif flash.now[:alert]
      .alert.alert-danger
        %button.close{"data-dismiss" => "alert", :type => "button"} ×
        = flash.now[:alert]
    - elsif flash[:alert]
      .alert.alert-warning
        %button.close{"data-dismiss" => "alert", :type => "button"} ×
        = flash[:alert]
    .container
      = yield

app/views/pins/_form.html.haml
= form_for pin, :html => { :multipart => true } do |f|
  - if pin.errors.any?
    #error_explanation
      %h2
        = pluralize(pin.errors.count, "error")
        prohibited this pin from being saved:
      %ul
        - pin.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :pin_image
    = f.file_field :pin_image
  .field
    = f.label :board
    = f.select :board_id, options_from_collection_for_select(current_user.boards, "id", "name")
  .actions
    = f.submit

app/views/pins/edit.html.haml
.col-md-6.col-md-offset-3
  %h1 Editing Pin
  = image_tag @pin.pin_image.url(:medium), class: 'img-responsive'
  = render 'form', pin: @pin
  = link_to 'Show', @pin
  |
  = link_to 'Back', pins_path

app/views/pins/index.html.haml
%p#notice= notice

.row.pin-grid.transitions-enabled
  - @pins.each do |pin|
    .col-md-3.pin-item
      .panel.panel-default.pin
        .panel-body
          = link_to image_tag(pin.pin_image.url(:medium)), pin
        .panel-footer.panel-custom
          %p= link_to pin.user.username, user_path(pin.user.username)
          %p= pin.description
          %p= pluralize(pin.likes.count, "like")
          - if pin.user == current_user
            %div
              = link_to 'Edit', edit_pin_path(pin)
              | #{link_to 'Delete', pin, method: :delete, data: {confirm: 'Are you sure?'}}
          - if user_signed_in? && pin.user != current_user
            %div
              = link_to 'Repost', repost_pin_path(pin), method: :post, data: {confirm: 'Are you sure?'}
              = link_to 'Like', like_pin_path(pin), method: :post, class: 'pull-right'

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
  %h1 New Pin
  = render 'form', pin: @pin
  = link_to 'Back', pins_path

app/views/pins/show.html.haml
%p#notice= notice
%p
  = @pin.description

%div
  = image_tag @pin.pin_image.url(:medium)

= link_to 'Edit', edit_pin_path(@pin)
|
= link_to 'Back', pins_path

app/views/users/show.html.haml
%h3
  = @user.username
%p
  = @user.bio
%div
  = image_tag @user.avatar.url(:thumb)

.row.pin-grid.transitions-enabled
  - @user.pins.each do |pin|
    .col-md-3.pin-item
      .panel.panel-default.pin
        .panel-body
          = link_to image_tag(pin.pin_image.url(:medium)), pin
        .panel-footer
          %p= link_to pin.user.username, user_path(pin.user.username)
          %p= pin.description
          - if pin.user == current_user
            %div
              = link_to 'Edit', edit_pin_path(pin)
              | #{link_to 'Delete', pin, method: :delete, data: {confirm: 'Are you sure?'}}

app/views/welcome/index.html.haml
.jumbotron
  %h1 Sweet
  %p.lead A Pinterest Replica for Dessert Lovers
  %p
    = link_to "Sign In", new_user_session_path, class: 'btn btn-primary btn-lg'
    or
    \#{link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary btn-lg'} today!